name: secure_gates_admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  awesome_dialog: any
  cupertino_icons: ^1.0.2
  dio: ^5.3.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.0
  flutter_image_compress: ^2.0.4
  flutter_phone_direct_caller: ^2.1.1
  flutter_tts: ^3.7.0
  fluttertoast: ^8.2.2
  go_router: ^10.0.0
  hooks_riverpod: ^2.3.7
  iconsax: ^0.0.8
  image_picker: ^1.0.1
  lottie: ^2.5.0
  path_provider: ^2.0.15
  rive: ^0.9.1
  shared_preferences: ^2.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Light.ttf
        - asset: assets/fonts/Ubuntu-Italic.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf

  assets:
    - assets/icons/visitor1.png
    - assets/icons/visitor-out.png
    - assets/icons/wrong-visitors.png
    - assets/icons/car-in.png
    - assets/icons/add-car.png
    - assets/icons/staff-in.png
    - assets/icons/staff-out.png
    - assets/icons/add-staff.png
    - assets/icons/car-out.png
